services:
  metadata-analysis:
    build: ./metadata_analysis
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload 
    ports: 
      - "8000:8000"
    volumes:
      - shared_data:/shared_data
      # - ./metadata_analysis:/app 
    environment:
      SHARED_DATA_PATH: /shared_data

  video-analysis:
    build: ./video_analysis 
    command: uvicorn server:app --host 0.0.0.0 --port 8888 --reload
    ports: 
      - "8888:8888"
    volumes:
      - shared_data:/shared_data
      # - ./video_analysis:/app 
    environment: 
      SHARED_DATA_PATH: /shared_data

  audio-analysis:
    build: ./audio_analysis 
    command: python app.py
    ports: 
      - "5000:5000"
    volumes:
      - shared_data:/shared_data
      # - ./audio_analysis:/app
    environment: 
      SHARED_DATA_PATH: /shared_data

  decision_block: 
    build: ./decision_block
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    volumes:
      - shared_data:/shared_data
      - ./decision_block:/app
    environment: 
      META_LINK: http://metadata-analysis:8000
      VIDEO_LINK: http://video-analysis:8888 
      AUDIO_LINK: http://audio-analysis:5000 
      SHARED_DATA_PATH: /shared_data
    ports: 
      - "8003:8003"
    depends_on: 
      - metadata-analysis 
      - video-analysis
      - audio-analysis

volumes:
  shared_data: