#!/usr/bin/env python3
"""
Video metadata analyzer: REAL vs AI classification.
Uses exiftool, SQLite statistical model and heuristic rules.
No screenshot detection — only video-specific logic.
"""

import subprocess
import json
import math
import sqlite3
import re
from datetime import datetime
from typing import Dict, List, Set, Tuple, Any

# ======================================================
# Константы – ключевые слова для поиска в названиях тегов
# ======================================================
CAMERA_TAG_PATTERNS: List[str] = [
    r'(?:^|[_-])make(?:$|[_-])',          # строго отдельное слово
    r'(?:^|[_-])model(?:$|[_-])',
    r'(?:^|[_-])lensmodel(?:$|[_-])?',    # допускает суффиксы вроде -eng-US
    r'(?:^|[_-])lensinfo(?:$|[_-])?',
    r'(?:^|[_-])iso(?:$|[_-])',
    r'(?:^|[_-])exposuretime(?:$|[_-])',
    r'(?:^|[_-])?fnumber',                # без левой границы, чтобы ловить irisfnumber
    r'(?:^|[_-])aperture(?:$|[_-])',
    r'(?:^|[_-])?focallength',            # уже ловилось, но для симметрии
    r'(?:^|[_-])flash(?:$|[_-])',
    r'(?:^|[_-])whitebalance(?:$|[_-])',
    r'(?:^|[_-])meteringmode(?:$|[_-])',
    r'(?:^|[_-])exposuremode(?:$|[_-])'
]

GPS_TAG_PATTERNS: List[str] = [
    r'\bgpslatitude\b', r'\bgpslongitude\b', r'\bgpsaltitude\b', r'\bgpsdatestamp\b'
]

RICHNESS_TAG_PATTERNS: List[str] = [
    r'\bduration\b', r'\btrackduration\b', r'\bmediaduration\b',
    r'\bvideoframerate\b', r'\bavgbitrate\b', r'\bimagewidth\b', r'\bimageheight\b',
    r'\bcompressorid\b', r'\bencodername\b',
    r'\bmake\b', r'\bmodel\b', r'\blensmodel\b',
    r'\bcreatetime\b', r'\bcreationdate\b', r'\bmodifydate\b',
    r'\bgpslatitude\b', r'\bgpslongitude\b'
]

KNOWN_CAMERAS: Set[str] = {
    "apple", "samsung", "xiaomi", "canon", "sony",
    "nikon", "fuji", "panasonic", "dji", "gopro"
}

AI_VIDEO_SOFTWARE: Set[str] = {
    "runway", "gen-2", "gen-3", "pika", "pika labs",
    "sora", "openai", "stable video diffusion", "svd",
    "modelscope", "zeroscope", "vidgen", "moonvalley",
    "kling", "hailuo", "luma",
    "lavf",          # ffmpeg-based encoder (часто в AI-генераторах)
    "ai generated",  # возможные строки в Title/Description
    "generated by",
    "diffusion",
    "comfyui",
    "automatic1111"
}

# Теги, игнорируемые при подсчёте статистической модели (плоский вывод)
IGNORE_TAGS = {
    "SourceFile", "FileName", "Directory", "FileSize",
    "FileModifyDate", "FileAccessDate", "FileInodeChangeDate",
    "FilePermissions", "ExifToolVersion", "FileType", "FileTypeExtension",
    "MIMEType", "MajorBrand", "MinorVersion", "CompatibleBrands",
    "MediaDataSize", "MediaDataOffset",
    # Структурные
    "MovieHeaderVersion", "TimeScale", "Duration",
    "PreferredRate", "PreferredVolume", "PreviewTime", "PreviewDuration",
    "PosterTime", "SelectionTime", "SelectionDuration", "CurrentTime",
    "NextTrackID", "TrackHeaderVersion", "TrackID", "TrackDuration",
    "TrackLayer", "TrackVolume", "ImageWidth", "ImageHeight",
    "CleanApertureDimensions", "ProductionApertureDimensions",
    "EncodedPixelsDimensions", "GraphicsMode", "OpColor",
    "CompressorID", "SourceImageWidth", "SourceImageHeight",
    "XResolution", "YResolution", "CompressorName", "BitDepth",
    "VideoFrameRate", "MatrixStructure", "MediaHeaderVersion",
    "MediaTimeScale", "MediaDuration", "MediaLanguageCode",
    "HandlerClass", "HandlerVendorID", "HandlerDescription",
    "MetaFormat", "HandlerType", "Balance",
    "AudioFormat", "AudioChannels", "AudioBitsPerSample",
    "AudioSampleRate", "PurchaseFileFormat", "ContentDescribes",
    "GenMediaVersion", "GenFlags", "GenGraphicsMode", "GenOpColor",
    "GenBalance", "FullFrameRatePlaybackIntent",
    "ImageSize", "Megapixels", "AvgBitrate", "Rotation",
    # Цветовые профили
    "ColorProfiles", "ColorPrimaries", "TransferCharacteristics",
    "MatrixCoefficients", "VideoFullRangeFlag", "PixelAspectRatio",
    # Предупреждения
    "Warning",
    # Даты (опционально)
    "CreateDate", "ModifyDate", "TrackCreateDate", "TrackModifyDate",
    "MediaCreateDate", "MediaModifyDate", "CreationDate", "ContentCreateDate"
}

# ======================================================
# Вспомогательные функции
# ======================================================
def _find_matching_patterns(extended_key: str, patterns: List[str]) -> Set[str]:
    """Возвращает множество паттернов, найденных в последней части ключа (после ':')."""
    tag_name = extended_key.split(':')[-1].lower()
    return {p for p in patterns if re.search(p, tag_name)}


def normalize_statistical_score(score: float) -> float:
    """Сигмоида для нормализации статистического score в [0,1]."""
    return 1.0 / (1.0 + math.exp(-score))


# ======================================================
# Извлечение метаданных через exiftool
# ======================================================
def get_metadata(path: str) -> Dict[str, Any]:
    """Плоский словарь метаданных (без групп), используется для статистической модели."""
    result = subprocess.run(
        ["exiftool/exiftool", "-j", str(path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    try:
        return json.loads(result.stdout)[0]
    except Exception:
        return {}


def get_extended_metadata(path: str) -> Dict[str, Any]:
    """Расширенные метаданные с префиксами групп (например, 'QuickTime:Make')."""
    result = subprocess.run(
        ["exiftool/exiftool", "-G", "-j", str(path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    try:
        return json.loads(result.stdout)[0]
    except Exception:
        return {}


# ======================================================
# Статистическая модель на основе частот тегов (SQLite)
# ======================================================
def calculate_metadata_likelihood(metadata_flat: Dict[str, Any],
                                  db_path: str = "video_tags.db") -> Tuple[List[Tuple[str, float]], float]:
    """
    Вычисляет средний логарифмический score на основе частот тегов в БД.
    Возвращает список вкладов (топ-20) и средний score.
    """
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    tags = [tag for tag in metadata_flat.keys() if tag not in IGNORE_TAGS]

    total_score = 0.0
    contributions = []
    matched = 0

    for tag in tags:
        cur.execute("SELECT Ratio FROM tag_frequencies WHERE Tag=?", (tag,))
        row = cur.fetchone()
        if not row:
            continue
        ratio = row[0]
        # ratio должно быть положительным, иначе log обрушится. Проверим.
        if ratio <= 0:
            continue
        log_ratio = math.log(ratio)
        total_score += log_ratio
        matched += 1
        contributions.append((tag, log_ratio))

    conn.close()
    contributions.sort(key=lambda x: abs(x[1]), reverse=True)

    if matched == 0:
        return contributions[:20], 0.0
    return contributions[:20], total_score / matched


# ======================================================
# Эвристические метрики для видео
# ======================================================
def compute_camera_score(metadata_ext: Dict[str, Any]) -> float:
    """Доля найденных паттернов камеры среди всех CAMERA_TAG_PATTERNS."""
    found: Set[str] = set()
    for key in metadata_ext:
        found.update(_find_matching_patterns(key, CAMERA_TAG_PATTERNS))
    return len(found) / len(CAMERA_TAG_PATTERNS)


def compute_known_camera_score(metadata_ext: Dict[str, Any]) -> float:
    """
    Проверяет наличие известного производителя, модели, объектива.
    Возвращает среднее по 4 флагам.
    """
    make_found = False
    model_found = False
    lens_model_found = False
    lens_info_found = False

    for key, val in metadata_ext.items():
        tag_last = key.split(':')[-1].lower()
        val_str = str(val).lower()
        if tag_last == 'make' and any(m in val_str for m in KNOWN_CAMERAS):
            make_found = True
        elif tag_last == 'model' and val:
            model_found = True
        elif tag_last == 'lensmodel' and val:
            lens_model_found = True
        elif tag_last == 'lensinfo' and val:
            lens_info_found = True

    return sum([make_found, model_found, lens_model_found, lens_info_found]) / 4.0


def compute_gps_score(metadata_ext: Dict[str, Any]) -> float:
    """Доля найденных GPS-паттернов."""
    found: Set[str] = set()
    for key in metadata_ext:
        found.update(_find_matching_patterns(key, GPS_TAG_PATTERNS))
    return len(found) / len(GPS_TAG_PATTERNS)


def compute_metadata_richness(metadata_ext: Dict[str, Any]) -> float:
    """Доля найденных паттернов, характерных для полных метаданных видео."""
    found: Set[str] = set()
    for key in metadata_ext:
        found.update(_find_matching_patterns(key, RICHNESS_TAG_PATTERNS))
    return len(found) / len(RICHNESS_TAG_PATTERNS)


def compute_ai_software_score(metadata_ext: Dict[str, Any]) -> float:
    """
    Ищет в значениях всех тегов ключевые слова генеративных моделей.
    Возвращает от 0 до 1 (порог на 2 совпадения).
    """
    blob = " ".join(str(v).lower() for v in metadata_ext.values())
    hits = sum(1 for kw in AI_VIDEO_SOFTWARE if kw in blob)
    return min(1.0, hits / 2.0)


def compute_timestamp_score(metadata_ext: Dict[str, Any]) -> float:
    """
    Проверяет согласованность дат создания и модификации.
    Если даты валидны и ModifyDate >= CreateDate — 1.0,
    иначе 0.0, при отсутствии дат — 0.5.
    """
    create_vals = []
    modify_vals = []
    for key, val in metadata_ext.items():
        tag_low = key.split(':')[-1].lower()
        if 'createdate' in tag_low or 'creationdate' in tag_low:
            create_vals.append(str(val))
        if 'modifydate' in tag_low:
            modify_vals.append(str(val))

    if not create_vals or not modify_vals:
        return 0.5

    try:
        # Берём первый подходящий
        c = datetime.strptime(create_vals[0][:19], "%Y:%m:%d %H:%M:%S")
        m = datetime.strptime(modify_vals[0][:19], "%Y:%m:%d %H:%M:%S")
        return 1.0 if m >= c else 0.0
    except Exception:
        return 0.5


# ======================================================
# Главный анализ
# ======================================================
def analyze(path: str) -> Dict[str, Any]:
    metadata_ext = get_extended_metadata(path)   # с группами
    metadata_flat = get_metadata(path)           # плоский

    contributions, statistical_score = calculate_metadata_likelihood(metadata_flat)
    statistical_score_norm = normalize_statistical_score(statistical_score)

    camera_score = compute_camera_score(metadata_ext)
    known_camera_score = compute_known_camera_score(metadata_ext)
    gps_score = compute_gps_score(metadata_ext)
    ai_sw_score = compute_ai_software_score(metadata_ext)
    richness = compute_metadata_richness(metadata_ext)
    timestamp_score = compute_timestamp_score(metadata_ext)

    # Расчёт вероятностей двух классов
    real_prob = (statistical_score_norm * 0.35 +
                 camera_score * 0.25 +
                 known_camera_score * 0.15 +
                 gps_score * 0.1 +
                 richness * 0.1 +
                 timestamp_score * 0.05)

    ai_prob = (ai_sw_score * 0.5 +
               (1.0 - richness) * 0.2 +
               (1.0 - camera_score) * 0.15 +
               (1.0 - statistical_score_norm) * 0.15)

    total = real_prob + ai_prob
    if total > 0:
        real_prob /= total
        ai_prob /= total
    else:
        real_prob = ai_prob = 0.5

    if real_prob > 0.6:
        verdict = "REAL"
    elif ai_prob > 0.6:
        verdict = "AI"
    else:
        verdict = "UNKNOWN"

    confidence = max(real_prob, ai_prob)

    return {
        "statistical_score": statistical_score,
        "statistical_score_norm": statistical_score_norm,
        "camera_score": camera_score,
        "known_camera_score": known_camera_score,
        "gps_score": gps_score,
        "ai_software_score": ai_sw_score,
        "metadata_richness": richness,
        "timestamp_score": timestamp_score,
        "real_probability": real_prob,
        "ai_probability": ai_prob,
        "verdict": verdict,
        "confidence": confidence,
        "contributions": contributions
        # "metadata_ext": metadata_ext
    }


# ======================================================
# Тестирование
# ======================================================
if __name__ == "__main__":
    test_files = [
        ("real_iphone", "./vid.MOV"),
        ("ai_example", "ai/ai (28).mp4")
    ]
    for name, filepath in test_files:
        result = analyze(filepath)
        print(name)
        print(json.dumps(result, indent=2))
        print()